// Shared fixture: loads Tools/oracle/oracle.json and Data/balance.json once.
//
// The oracle is generated by running the JS reference (Tools/oracle/dump-oracle.mjs),
// which is what brief §9 requires: "expected values come from running the JS reference".

#pragma once

#include <cstdio>
#include <cstdlib>
#include <string>

#include "AresCore/AresData.h"
#include "AresCore/AresJson.h"
#include "Harness/TestPaths.h"

namespace AresTest
{

inline const Ares::FJsonValue& Oracle()
{
	static Ares::FJsonValue Root;
	static bool bLoaded = false;
	if (!bLoaded)
	{
		std::string Error;
		if (!Ares::ParseJsonFile(AresTestPaths::OraclePath(), Root, Error))
		{
			std::printf("FATAL: cannot load oracle: %s\n", Error.c_str());
			std::printf("       regenerate with: node Tools/oracle/dump-oracle.mjs --ref <path-to-mars>\n");
			std::exit(2);
		}
		bLoaded = true;
	}
	return Root;
}

inline const Ares::FAresData& Balance()
{
	static Ares::FAresData Data;
	static bool bLoaded = false;
	if (!bLoaded)
	{
		std::string Error;
		if (!Ares::FAresData::LoadBalanceFile(AresTestPaths::BalancePath(), Data, Error))
		{
			std::printf("FATAL: cannot load balance.json: %s\n", Error.c_str());
			std::exit(2);
		}
		bLoaded = true;
	}
	return Data;
}

} // namespace AresTest
